import Navbar from "@/components/Navbar"
import Head from "next/head"
import Image from "next/image"

export default function Home() {
  return (
    <div className="APP bg-background w-screen min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </div>
  )
}
